/**
 * 从浏览器导出的 arena JSON 生成 seedArena.ts。
 * 会先跑 playGames 模拟生成基础阵容，再把玩家真实数据合并进去（玩家数据优先）。
 *
 * 用法：
 *   1. 在浏览器控制台运行：copy(localStorage.getItem('superAutoSan_arena'))
 *   2. 粘贴到 scripts/arena-export.json
 *   3. 运行：npx tsx scripts/importArena.ts
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const inputPath = resolve(__dirname, 'arena-export.json');
const outputPath = resolve(__dirname, '../src/engine/seedArena.ts');

const MAX_PER_WAVE = 20;

interface ArenaEntry {
  team: unknown[];
  savedAt: number;
}

// Step 1: Run playGames.ts first to get simulation baseline
console.log('=== 第一步：运行模拟生成基础阵容 ===\n');
execSync('npx tsx scripts/playGames.ts', { cwd: resolve(__dirname, '..'), stdio: 'inherit' });

// Step 2: Read the just-generated simulation seed
console.log('\n=== 第二步：读取模拟种子 ===');
const { SEED_ARENA: simSeed } = await import('../src/engine/seedArena');
const result: Record<string, ArenaEntry[]> = {};
let total = 0;

// Load sim data first
for (const [wave, entries] of Object.entries(simSeed)) {
  result[wave] = [];
  for (const entry of entries as any[]) {
    result[wave]!.push({ team: entry.team, savedAt: entry.savedAt ?? 0 });
    total++;
  }
}
console.log(`模拟种子：${total} 套阵容`);

// Step 3: Merge player data on top (player data has priority for variety)
if (existsSync(inputPath)) {
  console.log('\n=== 第三步：合并玩家真实数据 ===');
  const raw = readFileSync(inputPath, 'utf-8');
  const parsed = JSON.parse(raw);
  let playerCount = 0;

  for (const [wave, entries] of Object.entries(parsed)) {
    if (!Array.isArray(entries)) continue;
    if (!result[wave]) result[wave] = [];
    for (const item of entries) {
      if (result[wave]!.length >= MAX_PER_WAVE) break;
      if (item && typeof item === 'object' && 'team' in item) {
        result[wave]!.push(item as ArenaEntry);
      } else if (Array.isArray(item)) {
        result[wave]!.push({ team: item, savedAt: 0 });
      }
      playerCount++;
      total++;
    }
  }
  console.log(`玩家数据：${playerCount} 套阵容已合并`);
} else {
  console.log(`\n未找到 ${inputPath}，仅使用模拟数据`);
}

// Step 4: Write combined seed
const waves = Object.keys(result).map(Number).sort((a, b) => a - b);
const fileContent = `/**
 * Arena seed data: simulation + player data.
 * Generated by scripts/importArena.ts on ${new Date().toISOString()}.
 *
 * Loaded by ArenaStore on first run when localStorage is empty.
 */
import type { GeneralInstance } from '../data/types';

export interface SeededArenaEntry {
  team: GeneralInstance[];
  savedAt: number;
  comment?: string;
}

export const SEED_ARENA: Record<number, SeededArenaEntry[]> = ${JSON.stringify(result, null, 2)};
`;

writeFileSync(outputPath, fileContent, 'utf-8');
console.log(`\n=== 完成 ===`);
console.log(`已写入 ${outputPath}`);
console.log(`阵容分布：`);
for (const w of waves) {
  console.log(`  关卡 ${w}: ${result[w]!.length} 套阵容`);
}
console.log(`总共 ${total} 套阵容`);
